name: binder
channels:
  - conda-forge
dependencies:
#  - python <3.11.0 does not work yet on binder
  - python 
  - pip
  - cf-units
  - pycairo
  - pytest
  - nbmake
  - networkx
  - netCDF4
  - IPython 
  - jupytext
