name: test_windows_developer_installation
on:
  push:
    branches:
      - master
      - test

jobs:
  build:
    name: test-${{ matrix.os }}-${{ matrix.script }}
    timeout-minutes: 720
    strategy:
      matrix:
        os: [windows]
        script: [install_developer_conda.bat, install_developer_mamba.bat]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          #remote: # optional
          repository: MPIBGC-TEE/bgc_md2
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bgc_md2
          miniforge-version: latest
      - shell: bash -el {0}
        run: |
          conda --version
          which python
          python --version
      
      - name: Install dependencies
        run: |
          batch ${{ matrix.script }}

      #- name: run test suites
      #  run: |
      #    ./scripts/run_test_suites.sh
