name: test_conda_binder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        #remote: # optional
        repository: MPIBGC-TEE/bgc_md2
        token: ${{ secrets.ACCESS_TOKEN }}

    
    - name: Set up conda 
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: |
        which python
        python --version
    - name: Install dependencies
      run: |
        conda env create -f environment.yml 
  
    - name: run test suites
        run ./.
        github/workflows/run_test_suites.sh
