name: test_conda_binder

on:
  push:
    branches:
      - binder # only executed when something is pushed to the binder branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      defaults:
        run:
	  shell: bash -l {0}
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          #remote: # optional
          repository: MPIBGC-TEE/bgc_md2
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: anaconda, conda-forge
          activate-environment: binder
          auto-activate-base: false
          auto-update-conda: true
          environment-file: environment_free.yml

      - name: check python version
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          #conda env create -f environment.yml
          conda activate binder || true
            ./postBuild

      - name: run test suites
        run: |
          ./.github/workflows/run_test_suites.sh
